/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsCategoryIndexRouteImport } from './routes/tools.$category.index'
import { Route as ToolsCategorySlugRouteImport } from './routes/tools.$category.$slug'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCategoryIndexRoute = ToolsCategoryIndexRouteImport.update({
  id: '/tools/$category/',
  path: '/tools/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCategorySlugRoute = ToolsCategorySlugRouteImport.update({
  id: '/tools/$category/$slug',
  path: '/tools/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tools/$category/$slug': typeof ToolsCategorySlugRoute
  '/tools/$category/': typeof ToolsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tools/$category/$slug': typeof ToolsCategorySlugRoute
  '/tools/$category': typeof ToolsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tools/$category/$slug': typeof ToolsCategorySlugRoute
  '/tools/$category/': typeof ToolsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/privacy' | '/tools/$category/$slug' | '/tools/$category/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/tools/$category/$slug' | '/tools/$category'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/tools/$category/$slug'
    | '/tools/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ToolsCategorySlugRoute: typeof ToolsCategorySlugRoute
  ToolsCategoryIndexRoute: typeof ToolsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$category/': {
      id: '/tools/$category/'
      path: '/tools/$category'
      fullPath: '/tools/$category/'
      preLoaderRoute: typeof ToolsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$category/$slug': {
      id: '/tools/$category/$slug'
      path: '/tools/$category/$slug'
      fullPath: '/tools/$category/$slug'
      preLoaderRoute: typeof ToolsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ToolsCategorySlugRoute: ToolsCategorySlugRoute,
  ToolsCategoryIndexRoute: ToolsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
